name: Twitter test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Twitter Action
      uses: xorilog/twitter-action@0.1
      with:
          message: "test post"
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
           
